cinema/cinema/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('movies/', include('movies.urls')),
    path('users/', include('users.urls')),
]
# Добавляем маршруты для статических файлов в режиме разработки
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Добавляем маршруты для медиафайлов
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cinema/main/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='index'),  # Маршрут для страницы "Расписание"
    path('profile/', views.profile, name='profile'),  # Маршрут для страницы "Личный кабинет"
    path('theaters/', views.theaters, name='theaters'),  # Маршрут для страницы "Наши кинотеатры"
    path('upcoming/', views.upcoming, name='upcoming'),  # Маршрут для страницы "Скоро в кино"
    path('promotions/', views.promotions, name='promotions'),  # Маршрут для страницы "Акции"
    path('news/', views.news, name='news'),  # Маршрут для страницы "Новости"
]

cinema/movies/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.movies, name='movies'),
    path('movies/<int:movie_id>/', views.movie_detail, name='movie_detail'),
    path('movies/<int:movie_id>/booking/<int:session_id>/', views.show_seats_selection, name='booking_page'),
    # Страница выбора мест
    path('process_seats_selection/', views.process_seats_selection, name='process_seats_selection'),
    # Обработка выбранных мест
]

cinema/movies/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.contrib.auth.models import User
# class User(models.Model):
#     name = models.CharField(max_length=100)
#     email = models.EmailField(unique=True)
#     password = models.CharField(max_length=100)
#     role_choices = [
#         ('admin', 'Администратор'),
#         ('user', 'Пользователь')
#     ]
#     role = models.CharField(max_length=20, choices=role_choices)
#
#     def __str__(self):
#         return self.name
class Movie(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    release_date = models.DateField()
    director = models.CharField(max_length=100)
    genre = models.CharField(max_length=50)
    rating = models.DecimalField(max_digits=3, decimal_places=1, validators=[MinValueValidator(0), MaxValueValidator(10)])

    def __str__(self):
        return self.title


class CinemaHall(models.Model):
    hall_choices = [
        ('2D_1', 'Зал 1 - 2D'),
        ('2D_2', 'Зал 2 - 2D'),
        ('2D_3', 'Зал 3 - 2D'),
        ('3D_4', 'Зал 4 - 3D'),
        ('VIP_5', 'Зал 5 - VIP'),
        ('VIP_3D_6', 'Зал 6 - VIP 3D'),
    ]
    hall_name = models.CharField(max_length=10, choices=hall_choices)

    def __str__(self):
        return self.get_hall_name_display()

class Seat(models.Model):
    cinema_hall = models.ForeignKey(CinemaHall, on_delete=models.CASCADE)
    row_number = models.IntegerField()
    seat_number = models.IntegerField()
    is_reserved = models.BooleanField(default=False)

    def __str__(self):
        return f"Row {self.row_number}, Seat {self.seat_number} in {self.cinema_hall.get_hall_name_display()}"

class Session(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    cinema_hall = models.ForeignKey(CinemaHall, on_delete=models.CASCADE)
    start_time = models.DateTimeField()

    def __str__(self):
        return f"{self.movie.title} at {self.start_time}"

class Reservation(models.Model):
    movie_session = models.ForeignKey(Session, on_delete=models.CASCADE)
    seat = models.ForeignKey(Seat, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    user_email = models.EmailField()
    reservation_time = models.DateTimeField()

    def __str__(self):
        movie_title = self.movie.title if self.movie else "Unknown Movie"
        user_name = self.user.username if self.user else "Unknown User"
        return f"Reservation for {movie_title} by {user_name}"

class SessionSeat(models.Model):
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    seat = models.ForeignKey(Seat, on_delete=models.CASCADE)
    is_reserved = models.BooleanField(default=False)

    def __str__(self):
        return f"Seat {self.seat.seat_number} in session {self.session.id}"

cinema/movies/views.py
from django.shortcuts import render, get_object_or_404
from .models import Movie, Seat, Reservation, Session, SessionSeat
from django.utils import timezone
from django.http import HttpResponseRedirect
def movies(request):
    movies = Movie.objects.all()
    return render(request, 'movies/movies_list.html', {'movies': movies})

def movie_detail(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    return render(request, 'movies/movie_detail.html', {'movie': movie})




# def booking_page(request, movie_id, session_id):
#     # Ваш код для обработки страницы бронирования сеанса
#     return HttpResponse(f"Вы находитесь на странице бронирования фильма {movie_id} для сеанса {session_id}")
def show_seats_selection(request, movie_id, session_id):
    # Получаем места только для выбранного сеанса
    session_seats = SessionSeat.objects.filter(session_id=session_id, is_reserved=False)
    return render(request, 'movies/seats_selection.html', {'session_seats': session_seats, 'session_id': session_id})



def process_seats_selection(request):
    if request.method == 'POST':
        session_id = request.POST.get('session_id')
        selected_seats = request.POST.getlist('selected_seats')
        for seat_id in selected_seats:
            session_seat = SessionSeat.objects.get(session_id=session_id, seat_id=seat_id)
            session_seat.is_reserved = True
            session_seat.save()

            # Создание записи в таблице Reservation
            reservation = Reservation()
            reservation.movie_session = Session.objects.get(id=session_id)
            reservation.seat = session_seat.seat
            reservation.user_name = request.user.name  # Или любое другое значение, которое вы хотите использовать
            reservation.user_email = request.user.email  # Или любое другое значение, которое вы хотите использовать
            reservation.reservation_time = timezone.now()  # Импортировать: from django.utils import timezone
            reservation.save()

        return HttpResponseRedirect('/success/')  # Перенаправление на страницу успешного бронирования
    return HttpResponseRedirect('/error/')  # Перенаправление на страницу ошибки

cinema/movies/templates/movies/movie_detail.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %}Детали фильма - {{ movie.title }}{% endblock %}

{% block content %}
<section class="movie-detail-section">
    <div class="movie-detail">
        <img src="{{ movie.image.url }}" alt="{{ movie.title }}">
        <h2>{{ movie.title }}</h2>
        <p>{{ movie.description }}</p>
        <p><strong>Год выпуска:</strong> {{ movie.year }}</p>
        <p><strong>Режиссер:</strong> {{ movie.director }}</p>
        <p><strong>Жанр:</strong> {{ movie.genre }}</p>
        <p><strong>Рейтинг:</strong> {{ movie.rating }}</p>
    </div>

    <div class="movie-sessions">
        <h3>Сеансы</h3>
        <ul>
            {% for session in movie.session_set.all %}
                <li>
                    <a href="{% url 'movie_detail' movie.pk %}" class="movie-session-button">
                        <strong>Дата и время:</strong> {{ session.start_time }}
                        <br>
                        <strong>Место показа:</strong> {{ session.cinema_hall.get_hall_name_display }}
                    </a>
                </li>
            {% empty %}
                <li>Нет доступных сеансов</li>
            {% endfor %}
        </ul>
    </div>
</section>
{% endblock %}

cinema/movies/templates/movies/seats_selection.html
<!DOCTYPE html>
{% extends 'main/layout.html' %}
{% load static %}

{% block content %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Выбор места на сеанс</title>
    <link rel="stylesheet" href="{% static 'main/styles.css' %}"> <!-- Используйте для загрузки стилей -->
</head>
<body>
    <h1>Выберите места на сеанс</h1>
    <form action="{% url 'process_seats_selection' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="session_id" value="{{ session_id }}">
        <div class="seats">
           {% for session_seat in session_seats %}
                <input type="checkbox" name="selected_seats" value="{{ session_seat.seat.id }}" {% if session_seat.is_reserved %}disabled{% endif %}>
                <label {% if session_seat.is_reserved %}class="reserved"{% endif %}>Ряд: {{ session_seat.seat.row_number }}, Место: {{ session_seat.seat.seat_number }}</label><br>
           {% endfor %}
        </div>
        <button type="submit">Забронировать выбранные места</button>
    </form>
</body>
</html>

{% endblock %}