cinema/cinema/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('movies/', include('movies.urls')),
    path('users/', include('users.urls')),
]
# Добавляем маршруты для статических файлов в режиме разработки
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Добавляем маршруты для медиафайлов
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cinema/main/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='index'),  # Маршрут для страницы "Расписание"
    path('profile/', views.profile, name='profile'),  # Маршрут для страницы "Личный кабинет"
    path('theaters/', views.theaters, name='theaters'),  # Маршрут для страницы "Наши кинотеатры"
    path('upcoming/', views.upcoming, name='upcoming'),  # Маршрут для страницы "Скоро в кино"
    path('promotions/', views.promotions, name='promotions'),  # Маршрут для страницы "Акции"
    path('news/', views.news, name='news'),  # Маршрут для страницы "Новости"
]

cinema/users/urls.py
from django.urls import path
from .views import register_view, login_view, logout_view

urlpatterns = [
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),  # URL для выхода из системы
]

cinema/users/models.py
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.db import models

class CustomUser(AbstractUser):
    name = models.CharField(max_length=100)
    role_choices = [
        ('admin', 'Администратор'),
        ('user', 'Пользователь')
    ]
    role = models.CharField(max_length=20, choices=role_choices)
    groups = models.ManyToManyField(Group, related_name='custom_user_groups')
    user_permissions = models.ManyToManyField(Permission, related_name='custom_user_permissions')

    def __str__(self):
        return self.name

cinema/users/forms.py
from django import forms
from .models import CustomUser

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ['name', 'username', 'email', 'password']

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

cinema/users/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseNotAllowed
from django.shortcuts import render, redirect
from .forms import RegistrationForm, LoginForm
from django.urls import reverse
from .models import CustomUser

def register_view(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        role = request.POST.get('role')

        user = CustomUser(name=name, username=username, email=email, password=password, role=role)
        user.save()

        return redirect('users/login')  # Перенаправление на страницу входа после успешной регистрации

    return render(request, 'users/register.html')

def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(request, email=form.cleaned_data['email'], password=form.cleaned_data['password'])
            if user is not None:
                login(request, user)
                return redirect('main')
    else:
        form = LoginForm()
    return render(request, 'users/login.html', {'form': form})


def logout_view(request):
    if request.method == 'GET':
        logout(request)

        # После выхода из системы, перенаправляем пользователя на главную страницу
        return redirect(reverse('index'))  # Используем имя URL 'index', определенное в main.urls
    else:
        # Обработка других методов, если необходимо
        # Например, вернуть ошибку метода недопустимого запроса
        return HttpResponseNotAllowed(['GET'])

cinema/users/templates/users/login.html
<!DOCTYPE html>
{% extends 'main/layout.html' %}
{% block content %}
    <h2>Вход в систему</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Войти</button>
    </form>

    <!-- Добавляем кнопку "Зарегистрироваться" -->
    <a href="{% url 'register' %}"><button>Зарегистрироваться</button></a>
{% endblock %}

cinema/users/templates/users/register.html
<!DOCTYPE html>
{% extends 'main/layout.html' %}
{% block content %}
    <h2>Регистрация</h2>
    <form method="post">
        {% csrf_token %}
        <label for="id_name">Имя:</label>
        <input type="text" id="id_name" name="name"><br><br>

        <label for="id_username">Имя пользователя:</label>
        <input type="text" id="id_username" name="username"><br><br>

        <label for="id_email">Email:</label>
        <input type="email" id="id_email" name="email"><br><br>

        <label for="id_password">Пароль:</label>
        <input type="password" id="id_password" name="password"><br><br>

        <label for="id_role">Роль:</label>
        <select id="id_role" name="role">
            <option value="admin">Администратор</option>
            <option value="user">Пользователь</option>
        </select><br><br>

        <button type="submit">Зарегистрироваться</button>
    </form>
{% endblock %}